name: Expo Android APK Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  expo-build:
    name: Build APK via Expo Classic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install Dependencies
        run: npm install

      - name: Log in to Expo (guest account)
        run: expo login -u guest -p guest

      - name: Start Expo Classic Build (APK)
        run: |
          expo build:android -t apk --non-interactive
